name: Important numbers

on:
  workflow_dispatch:
    inputs:
      should_fail:
        description: 'Shall the step fail? (yes/no)'
        required: true
        type: string
        default: no

jobs:
  reminder: 
    runs-on: ubuntu-latest
    steps: 
    - name: Force Failure
      run: |
         if [ "${{ github.event.inputs.should_fail }}" == "yes" ]; then
          exit 1
         fi
    
  failure-handler:
    needs: reminder
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Print Birthday
      run: echo "Your birthday is 28 of May"
  
 
  
