name: Success if number input is seven or more!

on:
  workflow_dispatch:
    inputs:
      important:
        description: "Pick a number"
        required: true
        default: "5"
        type: number
     
jobs: 
  conditional_job:
    runs-on: ubuntu-latest
    steps:
      - name: Control input
        shell: bash
        run: |
          if [ ${{ github.event.inputs.important }} -ge 7 ]; then
            echo "Input is 7 or bigger."
          else
            echo "Do not run the job, important is less than 7"
            exit 1
          fi
      
    
      
