name: Success if number input is seven or more

on:
  workflow_dispatch:
    inputs:
      important:
      description: "Pick a number"
      required: true
      type: number
     
      
jobs: 
  conditional_job:
    runs-on: ubuntu-latest
    steps:
      -name: Control input
      if: ${{ github.events.inputs.important >= 7}}
      run: echo "Input is 7 or bigger."

    -name: Don´t run
    if: ${{ github.events.important < 7}}
    run: echo "Don´t run the job, important is less than 7"
      
    
      
